#!/bin/bash
# Convert audio files to mp3
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
#can I do this
for i in *.{wav,ogg,ac3,aac,flac}; do
    ffmpeg -i "$i"  -acodec libmp3lame "${i%.*}".mp3    
done
IFS=$SAVEIFS
