#!/bin/bash	
pactl set-default-sink 'alsa_output.pci-0000_00_1f.3.analog-stereo'
pactl set-sink-volume 'alsa_output.pci-0000_00_1f.3.analog-stereo' 85%
pactl set-default-source 'alsa_input.pci-0000_00_1f.3.analog-stereo'
pactl set-source-volume 'alsa_input.pci-0000_00_1f.3.analog-stereo' 85%

notify-send "Audio set to Line"
