#!/bin/bash
pactl set-default-sink 'alsa_output.pci-0000_01_00.1.hdmi-stereo'
pactl set-sink-volume 'alsa_output.pci-0000_01_00.1.hdmi-stereo' 75%
pactl set-default-source 'alsa_input.usb-Sonix_Technology_Co.__Ltd._HD_1080P_PC-Camera_SN0001-02.analog-stereo'
pactl set-source-volume 'alsa_input.usb-Sonix_Technology_Co.__Ltd._HD_1080P_PC-Camera_SN0001-02.analog-stereo' 75%

notify-send "Audio set to HDMI"
