#!/bin/bash
# This script takes the branch name in the format WRNNNNN-Other-text
# It strips the WR number out and puts the new wr+message as commit message
# if no errors, it then pushes the current  branch up to origin
branch=$(git rev-parse --abbrev-ref HEAD);
if [ $branch == "PROD" ]; then
    echo "You are on PROD branch, no commits allowed";
else
  message=$(echo "$branch"|cut -d- -f2-);
  wr=$(echo "WR33435-This-is-it"|cut -d- -f1);
  wr=$(echo "[#$wr]")
  echo git commit -m \""$wr $message"\";
  #if  git commit -m \" "$wr $message" \" 
  #then
     echo git push -u origin $branch;
  #fi
fi
