#!/bin/bash
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
fi
site=$1
echo "Creating site ${site}"
# Create wwwroot
mkdir /var/www/${site}
chmod -R 755 /var/www/${site}
chown -R www-data:www-data /var/www/${site}
# Setup vhost on 80
echo "Setting up vhost files"
sed  "s/\%servername\%/${site}/g" /etc/apache2/sites-available/template.conf > /etc/apache2/sites-available/${site}.conf
cat /etc/apache2/sites-available/${site}.conf
# Setup vhost ssl on 443
sed  "s/\%servername\%/${site}/g" /etc/apache2/sites-available/template.ssl.conf > /etc/apache2/sites-available/${site}.ssl.conf
cat /etc/apache2/sites-available/${site}.ssl.conf
# create log directory
mkdir /var/log/${site}
# Create certificate for site
# Variables for certificate creation
domain=${site}
commonname=$domain
#Change to your company details
# /C=NL/ST=Zuid Holland/L=Rotterdam/O=Sparkling Network/OU=IT Department/CN=ssl.raymii.org
country="au"
state="Victoria"
loc="Melbourne" #location
o="ESA" #organization
ou="DT&L" #oganizationalunit
email="peter.kelly@esa.edu.au"
# Go ahead and make it already

echo "Creating Cert"
echo mkdir -p /etc/apache2/ssl/${site}
mkdir -p /etc/apache2/ssl/${1}
echo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/${1}/${1}.key -out /etc/apache2/ssl/${1}/${1}.crt "/C=${country}/ST=${state}/L=${loc}/O=${o}/OU=${ou}/CN=${site}//emailAddress=${email}"
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/${1}/${1}.key -out /etc/apache2/ssl/${1}/${1}.crt -subj "/C=${country}/ST=${state}/L=${loc}/O=${o}/OU=${ou}/CN=${site}//emailAddress=${email}" 

# Enable site
echo "Enabling site"
echo a2ensite ${site}.conf
a2ensite ${site}.conf -q
echo a2ensite ${site}.ssl.conf 
a2ensite ${site}.ssl.conf -q
systemctl reload apache2

# Add to server.txt
echo ${site} >> ~/server.txt
