#!/bin/bash
# files need to be in the foramt tt-artist-albumtitle-tracktitle.mp3
# call with  ./mp3tagem 2001  24 album_artist

artist=  #artist
genre=   #genre
year=    #year

while getopts "a:y:g:h" param; do
    case "${param}" in

    a)    album_artist="$OPTARG";;  

    g)    genre="$OPTARG";;
         
    y)    year="$OPTARG";;
          
    h)   printf "Usage %s: -a artist  -y #### -g ### \n"
         printf "example: mp3tagem -y 2001  -g 24 -a \"Rick Astley\" \n"
         printf "Common Genres: \n"
         printf "0. Blues        10. New Age    20. Alternative   30. Fusion     40. AlternRock 50. Darkwave \n"
         printf "1. Classic Rock 11. Oldies     21. Ska           31. Trance     41. Bass       51. Techno-Industrial \n"
         printf "2. Country      12. Other      22. Death Metal   32. Classical  42. Soul       52. Electronic \n"
         printf "3. Dance        13. Pop        23. Pranks        33. Instrument 43. Punk       53. Pop-Folk \n"
         printf "4. Disco        14. R&B        24. Soundtrack    34. Acid       44. Space      54. Eurodance \n"
         printf "5. Funk         15. Rap        25. Euro-Techno   35. House      45. Meditative 55. Dream \n"
         printf "6. Grunge       16. Reggae     26. Ambient       36. Game       46. Inst Pop   56. Southern Rock \n"
         printf "7. Hip-Hop      17. Rock       27. Trip-Hop      37. Sound Clip 47. Inst Rock  57. Comedy \n"
         printf "8. Jazz         18. Techno     28. Vocal         38. Gospel     48. Ethnic     58. Cult \n"
         printf "9. Metal        19. Industrial 29. Jazz+Funk     39. Noise      49. Gothic     59. Gangsta \n"
         exit 2;;
    
    ?)   printf "Usage %s: -a artist  -y #### -g ### \n" 
         printf "example: mp3tagem -y 2001  -g 24 -a \"Rick Astley\" \n"
         exit 2;;
    esac
done
shift $((OPTIND-1))

track=0;
if [ ! -z "${album_artist}" ] && [ ! -z "${year}" ] && [ ! -z "${genre}" ]; then
   SAVEIFS=$IFS
   IFS=$(echo -en "\n\b")
   for f in $(ls|grep mp3); do 
      fn="$f";
      fn="${fn%.*}"
      track=$(echo "$fn"|cut -f1 -d-);
      artist=$(echo "$fn"|cut -f2 -d-);
      albumtitle=$(echo "$fn"|cut -f3 -d-);
      title=$(echo "$fn"|cut -f4 -d-);
      id3v2 -g ${genre} -y ${year} -a "${artist}" -A "${albumtitle}" -t "${title}" -T "${track}" --TPE2 "${album_artist}" "$f";
      echo "Processed: $track: $title - $artist";   
   done;     
   IFS=SAVEIFS
else
    printf "Usage %s: -a [artist]  -y [####] -g [###] \n" $0
    exit 2
fi

# ./mp3tagem year genre
#  0. Blues
#  1. Classic Rock
#  2. Country
#  3. Dance
#  4. Disco
#  5. Funk
#  6. Grunge
#  7. Hip-Hop
#  8. Jazz
#  9. Metal
# 10. New Age
# 11. Oldies
# 12. Other
# 13. Pop
# 14. R&B
# 15. Rap
# 16. Reggae
# 17. Rock
# 18. Techno
# 19. Industrial
# 20. Alternative
# 21. Ska
# 22. Death Metal
# 23. Pranks
# 24. Soundtrack
# 25. Euro-Techno
# 26. Ambient
# 27. Trip-Hop
# 28. Vocal
# 29. Jazz+Funk
# 30. Fusion
# 31. Trance
# 32. Classical
# 33. Instrumental
# 34. Acid
# 35. House
# 36. Game
# 37. Sound Clip
# 38. Gospel
# 39. Noise
# 40. AlternRock
# 41. Bass
# 42. Soul
# 43. Punk
# 44. Space
# 45. Meditative
# 46. Instrumental Pop
# 47. Instrumental Rock
# 48. Ethnic
# 49. Gothic
# 50. Darkwave#
# 51. Techno-Industrial
# 52. Electronic
# 53. Pop-Folk
# 54. Eurodance
# 55. Dream
# 56. Southern Rock
# 57. Comedy
# 58. Cult
# 59. Gangsta
# 60. Top 40
# 61. Christian Rap
# 62. Pop/Funk
# 63. Jungle
# 64. Native American
# 65. Cabaret
# 66. New Wave
# 67. Psychadelic
# 68. Rave
# 69. Showtunes
# 70. Trailer
# 71. Lo-Fi
# 72. Tribal
# 73. Acid Punk
# 74. Acid Jazz
# 75. Polka
# 76. Retro
# 77. Musical
# 78. Rock & Roll
# 79. Hard Rock
#The following genres are Winamp extensions
# 80. Folk
# 81. Folk-Rock
# 82. National Folk
# 83. Swing
# 84. Fast Fusion
# 85. Bebob
# 86. Latin
# 87. Revival
# 88. Celtic
# 89. Bluegrass
# 90. Avantgarde
# 91. Gothic Rock	
#97. Chorus
#98. Easy Listening
#99. Acoustic
#100. Humour
#101. Speech
#102. Chanson
#103. Opera
#104. Chamber Music
#105. Sonata
#106. Symphony
#107. Booty Bass
#108. Primus
#109. Porn Groove
#110. Satire
#111. Slow Jam
#112. Club
#113. Tango
#114. Samba
#115. Folklore
#116. Ballad
##117. Power Ballad
#118. Rhythmic Soul
#119. Freestyle
#120. Duet
#121. Punk Rock
#122. Drum Solo
#123. A capella
#124. Euro-House
#125. Dance Hall
